"""Publication-quality figure helpers for FINS coursework."""

from __future__ import annotations

import os

import matplotlib

if "MPLBACKEND" not in os.environ:
    matplotlib.use("Agg", force=False)

from .export import (
    FigureContext,
    WordFigureEntry,
    WordFigureSpec,
    export_figure_bundle,
    export_word_figure,
    insert_figure_docx,
    insert_figures_docx,
    save_figure,
    word_figure_spec,
)
from .plotly_ft import apply_ft_plotly_layout, export_plotly_image, ft_plotly_template
from .plots import (
    NBER_RECESSIONS,
    RecessionWindow,
    add_nber_recession_shading,
    add_source_note,
    area_balance_plot,
    bar_plot,
    bubble_matrix_plot,
    bubble_scatter_plot,
    calendar_heatmap,
    connected_scatter_plot,
    correlation_heatmap,
    cumulative_returns_plot,
    distribution_comparison_plot,
    distribution_plot,
    diverging_bar_plot,
    drawdown_plot,
    dumbbell_plot,
    ecdf_plot,
    grouped_bar_plot,
    indexed_time_series_plot,
    lollipop_plot,
    mean_return_bar_plot,
    proportional_stacked_bar_plot,
    recession_windows_for_range,
    rolling_stat_plot,
    scatter_plot,
    slope_chart,
    small_multiples,
    stacked_area_plot,
    stacked_bar_plot,
    time_series_plot,
    uncertainty_band_plot,
    value_heatmap,
)
from .suite import (
    DataFrameProfile,
    FigurePlanItem,
    FigureSuiteResult,
    GeneratedFigure,
    create_figure_suite,
    plan_figure_suite,
    profile_dataframe,
)
from .theme import FT_BACKGROUND, FT_COLORS, apply_theme, figure_style, theme_rc
from .validation import (
    FigureIssue,
    infer_return_scale,
    validate_axes_labels,
    validate_category_label_count,
    validate_display_labels,
    validate_docx_images_fit_page,
    validate_equal_subplot_widths,
    validate_figure_context,
    validate_horizontal_grid,
    validate_image_not_blank,
    validate_legend_present,
    validate_markers_within_axes,
    validate_no_text_overlap,
    validate_no_tick_label_overlap,
    validate_series_identification,
    validate_titles_within_canvas,
    validate_unique_series_colors,
    validate_word_readability,
)

__all__ = [
    "FT_BACKGROUND",
    "FT_COLORS",
    "NBER_RECESSIONS",
    "DataFrameProfile",
    "FigureContext",
    "FigureIssue",
    "FigurePlanItem",
    "FigureSuiteResult",
    "GeneratedFigure",
    "RecessionWindow",
    "WordFigureEntry",
    "WordFigureSpec",
    "add_nber_recession_shading",
    "add_source_note",
    "apply_ft_plotly_layout",
    "apply_theme",
    "area_balance_plot",
    "bar_plot",
    "bubble_matrix_plot",
    "bubble_scatter_plot",
    "calendar_heatmap",
    "connected_scatter_plot",
    "correlation_heatmap",
    "create_figure_suite",
    "cumulative_returns_plot",
    "distribution_comparison_plot",
    "distribution_plot",
    "diverging_bar_plot",
    "drawdown_plot",
    "dumbbell_plot",
    "ecdf_plot",
    "export_figure_bundle",
    "export_plotly_image",
    "export_word_figure",
    "figure_style",
    "ft_plotly_template",
    "grouped_bar_plot",
    "indexed_time_series_plot",
    "infer_return_scale",
    "insert_figure_docx",
    "insert_figures_docx",
    "lollipop_plot",
    "mean_return_bar_plot",
    "plan_figure_suite",
    "profile_dataframe",
    "proportional_stacked_bar_plot",
    "recession_windows_for_range",
    "rolling_stat_plot",
    "save_figure",
    "scatter_plot",
    "slope_chart",
    "small_multiples",
    "stacked_area_plot",
    "stacked_bar_plot",
    "theme_rc",
    "time_series_plot",
    "uncertainty_band_plot",
    "validate_axes_labels",
    "validate_category_label_count",
    "validate_display_labels",
    "validate_docx_images_fit_page",
    "validate_equal_subplot_widths",
    "validate_figure_context",
    "validate_horizontal_grid",
    "validate_image_not_blank",
    "validate_legend_present",
    "validate_markers_within_axes",
    "validate_no_text_overlap",
    "validate_no_tick_label_overlap",
    "validate_series_identification",
    "validate_titles_within_canvas",
    "validate_unique_series_colors",
    "validate_word_readability",
    "value_heatmap",
    "word_figure_spec",
]
