[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#A51C30"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F2EE"
textColor = "#262A33"
font = "sans serif"
